### ISSUE TITLE
Unificar botons

### ISSUE THREAD

**Issue by andriusmp** [andriusmp/edit_org#1]
Tots els botons:
- La tipo no hauria de tenir ombra blanca --> Això aplica a tots els texts, sempre sense ombra
![image](https://user-images.githubusercontent.com/42779858/90403885-e4ba6a00-e0a1-11ea-83c3-58d108eda21e.png)
![image](https://user-images.githubusercontent.com/42779858/90403916-edab3b80-e0a1-11ea-81e1-b9d6b7489b20.png)

- La font ha d'estar amb la tipo Circular Std Bold
- Espaiat dintre de la capsa sempre el mateix (per exemple, els botons check-all/uncheck-all dels resultats tenen espaiats més petits)

**Comment by codstar** [comment]
Fet a local.

**Comment by andriusmp** [comment]
- Tipo: OK
- Tipo: no hauria de ser la Circular Std en negreta, si no la Circular Std Bold
- Espaiat: OK

**Comment by andriusmp** [comment]
OK
