### ISSUE TITLE
Colors dels checkbox

### ISSUE THREAD

**Issue by andriusmp** [andriusmp/edit_org#10]
És possible canviar el color dels checkbox seleccionats per a que no siguin blau sino ocres?
Proposta:
![image](https://user-images.githubusercontent.com/42779858/90405731-762adb80-e0a4-11ea-99cb-ee70ce6cc190.png)

Ara mateix està:
![image](https://user-images.githubusercontent.com/42779858/90405756-804cda00-e0a4-11ea-9462-20c0d7139421.png)

**Comment by codstar** [comment]
Fet a local.

**Comment by andriusmp** [comment]
OK
