### ISSUE TITLE
Informació addicional inventari

### ISSUE THREAD

**Issue by andriusmp** [andriusmp/edit_org#11]
Les àrees de les capses que donen informació adicional a l'inventari no estan alineades amb les capses de l'inventari.
![image](https://user-images.githubusercontent.com/42779858/90406408-665fc700-e0a5-11ea-8900-5566b3fc6323.png)

Per altra banda, la capsa d'ajuda d'escenari hauria d'estar tota amb la mateixa mida de tipo (14px) i amb espaiat entre el títol i el text:
![image](https://user-images.githubusercontent.com/42779858/90406575-a7f07200-e0a5-11ea-9295-636f87eb7653.png)

**Comment by codstar** [comment]
Fet a local.

**Comment by andriusmp** [comment]
OK
