### ISSUE TITLE
Botons d'impacte d'escenari

### ISSUE THREAD

**Issue by andriusmp** [andriusmp/edit_org#12]
Els botons marcar/desmarcar s'haurien de posar just a sobre de les categories, mentre que els de mostrar i exportar, haurien de centrar-se al mig de la pantalla
![image](https://user-images.githubusercontent.com/42779858/90407164-75934480-e0a6-11ea-9e24-32b4ea554658.png)

**Comment by codstar** [comment]
Fet a local.

**Comment by andriusmp** [comment]
OK
