### ISSUE TITLE
Icones de resultats

### ISSUE THREAD

**Issue by andriusmp** [andriusmp/edit_org#14]
Adaptar els colors de les icones 'taules', 'gràfics', 'interpretació' a la proposta.
Proposta:
![image](https://user-images.githubusercontent.com/42779858/90407954-6e206b00-e0a7-11ea-8e54-6f080f63a865.png)

Ara està:
![image](https://user-images.githubusercontent.com/42779858/90407912-5f39b880-e0a7-11ea-81c4-ea25e4d954c8.png)

Els espais entre icones haurien de ser els mateixos

**Comment by codstar** [comment]
Fet a local.

**Comment by andriusmp** [comment]
OK
