### ISSUE TITLE
Gràfics de barres i de sectors de resultats

### ISSUE THREAD

**Issue by andriusmp** [andriusmp/edit_org#16]
1/ La llegenda hauria de situar-se a la dreta dels combobox.
2/ L'espaiat entre elements hauria de ser sempre el mateix (en el cas del gràfic de sectors, hi ha espaiats diferents). Proposta de com hauria de quedar:
![image](https://user-images.githubusercontent.com/42779858/90409995-1f280500-e0aa-11ea-81f2-5608bc827f5c.png)
![image](https://user-images.githubusercontent.com/42779858/90410043-2c44f400-e0aa-11ea-8089-54e71120a444.png)

3/ El gràfic hauria de quedar centrat al mig (horitzontalment) de la capsa
4/ El botó show results al gràfic de sectors queda massa enganxat al segon combobox
![image](https://user-images.githubusercontent.com/42779858/90410374-9362a880-e0aa-11ea-8ff1-9a0cfe977334.png)
5/ Les línies valors de referència dels gràfics haurien de ser de color gris (el mateix gris del fons de la èdit #cccccc)
![image](https://user-images.githubusercontent.com/42779858/90410875-37e4ea80-e0ab-11ea-8332-e8653227fc88.png)
6/ Caldria reduir l'espai que queda a sota dels gràfics

**Comment by codstar** [comment]
Fet a local. 

Comentaris:

1)  y 2) Canviar això seria prou costós ja que la gràfica i la llegenda es generen de forma dinàmica i automàtica depenent de les dades a mostrar. A més, fer codi per a modificar la gràfica després de generada no donaria bons resultats (massa variabilitat a dades d'entrada)

6) Ajustar les dimensions d'aquestes gràfiques també es molt dificil per la quantitat de dades i la variabilitat en la quantitat d'etapes (i de la llargaria dels noms). He ajustat alguna grafica, pero si les ajuste massa no es veuran bé si hi ha massa etapes o amb noms massa llargs. Aqui si es podria fer codi per a ajustar les dimensions depenent de les dades d'entrada pero crec que el temps necessari per fer-ho no compensa el resultat. Que penseu?

**Comment by andriusmp** [comment]
1 i 2. OK, deixe-m'ho així doncs.
3. OK
4. OK
5. Ara només han quedat línies en els eixos 0% i 100%. És possible que n'hi hagi cada 20% per a facilitar la lectura de l'usuari?

**Comment by codstar** [comment]
5. Jo si veig linies horitzontals pel mig. El que passa es que aquestes linies de referencia es generen de manera automàtica   depenent de les dades del gràfic, a voltes es cada 20% i a voltes es cada 50%. Voleu que dedique temps a investigar per a intentar forçar que sempre surtin cada 20%?

**Comment by andriusmp** [comment]
OK, deixem-ho tal com està doncs!
