### ISSUE TITLE
Gràfic comparativa d'escenaris: Impactes totals per unitat de producció

### ISSUE THREAD

**Issue by andriusmp** [andriusmp/edit_org#17]
El gràfic ha quedat molt estirat, no hi cap a la pantalla
![image](https://user-images.githubusercontent.com/42779858/90411374-f739a100-e0ab-11ea-959e-578063ad0e91.png)

**Comment by codstar** [comment]
Fet a local.

**Comment by andriusmp** [comment]
OK
