### ISSUE TITLE
Panell de supervisor

### ISSUE THREAD

**Issue by andriusmp** [andriusmp/edit_org#18]
1/ Les icones han quedat una mica petites respecte a la proposta
Proposta:
![image](https://user-images.githubusercontent.com/42779858/90411634-5a2b3800-e0ac-11ea-802c-e070320e5f4f.png)

Ara mateix està:
![image](https://user-images.githubusercontent.com/42779858/90411597-4c75b280-e0ac-11ea-91d7-fad6b952fcc1.png)

2/ El nom i correu de l'usuari hauria d'estar centrat horitzontalment
3/ Hi ha una línea mostassa a sota que no hauria d'estar
4/ L'ombra gris per visualitzar la icona sobre la que està el mouse no és rodona, i queda una mica raro
![image](https://user-images.githubusercontent.com/42779858/90411907-b8581b00-e0ac-11ea-8e56-0628dd08aed0.png)

5/ Hi ha diverses icones d'acció que han quedat quadrades, haurien de ser rodones:
![image](https://user-images.githubusercontent.com/42779858/90412233-27ce0a80-e0ad-11ea-82cb-1066ade333e0.png)
![image](https://user-images.githubusercontent.com/42779858/90412252-2bfa2800-e0ad-11ea-855a-8738b2857308.png)
![image](https://user-images.githubusercontent.com/42779858/90412301-3e746180-e0ad-11ea-81e3-9dacba63c600.png)

**Comment by codstar** [comment]
Fet a local.

**Comment by andriusmp** [comment]
1/ OK
2/ OK
3/ OK
4/ OK
5/ OK
