### ISSUE TITLE
Unificació de finestres emergents

### ISSUE THREAD

**Issue by andriusmp** [andriusmp/edit_org#19]
Caldria unificar les finestres emergents:
- Barra superior groga amb text gris inèdit
- L'ordre dels botons hauria de ser sempre el mateix
- Quan els botons es marquen amb color, ha de ser el taronja inèdit (ara mateix en alguns casos d'esborrat és vermell)

Un exemple amb la finestra d'esborrat de de client:
Ara està:
![image](https://user-images.githubusercontent.com/42779858/90762742-d3619f80-e2e5-11ea-97ba-9e9287285a03.png)
![image](https://user-images.githubusercontent.com/42779858/90763807-a31b0080-e2e7-11ea-884c-8bb83a7e0023.png)

Proposta de com hauria d'estar:
![image](https://user-images.githubusercontent.com/42779858/90763743-85e63200-e2e7-11ea-9634-83f7bb6dec34.png)

**Comment by codstar** [comment]
Fet a local.

**Comment by andriusmp** [comment]
OK
