### ISSUE TITLE
Inventari - parámetres de qualitat de l'aigua

### ISSUE THREAD

**Issue by andriusmp** [andriusmp/edit_org#20]
La taula de paràmetres de qualitat de l'aigua és més ampla que la resta de l'inventari, pel que sembla que engloba la resta.
![image](https://user-images.githubusercontent.com/42779858/90766123-5802ec80-e2eb-11ea-8f69-a4355a378489.png)

**Comment by codstar** [comment]
Fet a local.

**Comment by andriusmp** [comment]
OK
