### ISSUE TITLE
[Importar plantilla d'escenari] Botó enrere

### ISSUE THREAD

**Issue by andriusmp** [andriusmp/edit_org#22]
La pantalla d'importar la plantilla d'escenari no té botó 'Enrere', pel que si no es vol completar l'acció, cal fer servir el 'enrere' del navegador, i en ocasions provoca un error de càrrega de formulari.
![image](https://user-images.githubusercontent.com/42779858/90891157-92d45580-e3bb-11ea-9243-b81cf23265ee.png)

**Comment by codstar** [comment]
Fet a local.

**Comment by andriusmp** [comment]
OK
