### ISSUE TITLE
[Resultats] Unificació de valors relatius i filtrar elements < del %

### ISSUE THREAD

**Issue by andriusmp** [andriusmp/edit_org#23]
Quan calculem els resultats d'un escenari, només es mostren els valors relatius > que el % fixat.
Quan fem comparativa d'escenaris, es mostren els valors relatius > que el % fixat + tots els valors d'etapa --> així és com hauria de funcionar també pels resultats d'escenari.

A més, dels elements que tinguin un % < del % fixat, cal filtrar la fila, no només deixar d'ensenyar el resultat.

**Comment by codstar** [comment]
Fet a local.

**Comment by andriusmp** [comment]
OK
