### ISSUE TITLE
Imatge a la pantalla d'inventari

### ISSUE THREAD

**Issue by andriusmp** [andriusmp/edit_org#24]
La imatge que es mostra a la pantalla d'inventari:

- mostra una icona de 'error al carregar la imatge' quan el centre de treball associat no té cap imatge
![image](https://user-images.githubusercontent.com/42779858/90887203-391c5d00-e3b4-11ea-96e3-2f251e57e8f9.png)

- mostra la imatge associada al centre de treball corresponent sense adaptar-la a l'amplada de la pantalla:
![image](https://user-images.githubusercontent.com/42779858/90914182-bad4b080-e3dd-11ea-9c46-9a5a18902b46.png)

**Comment by codstar** [comment]
Fet a local.
Respecte a "adaptar la imatge a l'amplada de la pantalla": si, com està s'adapta a l'amplaria, pero entenc que ho veieu massa gran si la imatge es gran. El que he fet es limitar l'amplaria de la imatge a un màxim de 200 pixels.

**Comment by andriusmp** [comment]
Ok, però ara queda un pèl petita. Podem pujar-ho a 400?

**Comment by codstar** [comment]
Fet a local.

**Comment by andriusmp** [comment]
OK
