### ISSUE TITLE
[Comparativa d'escenaris] Filtratge d'escenaris a comparar

### ISSUE THREAD

**Issue by andriusmp** [andriusmp/edit_org#25]
Els filtres que s'apliquen a l'hora de seleccionar els escenaris, no s'haurien d'aplicar als dos escenaris a comparar a la vegada, perquè això inhabilita les comparatives entre categories de centres de treball diferents i períodes diferents.

És a dir, hi hauria d'haver dos combos més de selecció de categoria de centre de treball i de període, que apliquessin al segon escenari.

![image](https://user-images.githubusercontent.com/42779858/91453426-fd840600-e87f-11ea-9645-dd1aef9c3f63.png)

**Comment by codstar** [comment]
Fet a local.

**Comment by andriusmp** [comment]
OK, però el text actual ara no ajuda a entendre que els tres primers combos fan referència al primer escenari i els 3 últims, al segon. Podem ajustar els textos? Entenc que haurem de refer les traduccions, però caldria modificar la base d'anglès perquè fos:

- First scenario: Workcenter category
- First scenario: Scenario period
- First scenario
- Second scenario: Workcenter category
- Second scenario: Scenario period
- Second scenario

**Comment by codstar** [comment]
Fet a local.

**Comment by andriusmp** [comment]
OK
