### ISSUE TITLE
[Resultats] Taules de resultats

### ISSUE THREAD

**Issue by andriusmp** [andriusmp/edit_org#26]
Quan les taules de resultats son més amples que l'ample de pantalla:

- Agregació d'escenaris, comparativa d'escenaris, comparativa anual, per categoria de centre de treball --> No tenen scroll horitzontal, pel que la taula se surt de la pantalla.
- Resultats d'escenari, resultats globals anuals --> Té scroll horitzontal, però està ubicat a sota de la taula. Això fa que l'usuari hagi de baixar fins a baix de tot per poder moure's per la taula. Podem afegir scroll també a la part superior de la taula?

Per altra banda, seria possible fixar la primera fila i la primera columna del a taula, de manera que quan l'usuari fa scroll per la taula no perdi aquestes referències?

**Comment by codstar** [comment]
Fet a local.

Afegir el scroll horizontal a la part superior es una mica complicat, pero amb les modificacions que he fet crec que ja no farà falta.

**Comment by andriusmp** [comment]
OK

**Comment by marianafm23** [comment]
Una pregunta, la primera fila no es pot bloquejar? A la que baixes una mica ja perds de vista quina columna és cada impacte.

**Comment by codstar** [comment]
Sí, de fet això es el que he implementat i funciona be a Firefox. Per el teu comentari he vist que a Chrome no funcionava per un bug del propi Chrome. He afegit una modificació per a que funcione també eh Chrome. (Fet a local)

**Comment by andriusmp** [comment]
OK
