### ISSUE TITLE
Scroll-down clients

### ISSUE THREAD

**Issue by andriusmp** [andriusmp/edit_org#29]
La tipografia del desplegable de clients a la pantalla de projectes, està en tipo Noe Display (reservada només per h1). Hauria de ser Circular Std Bold.

![image](https://user-images.githubusercontent.com/42779858/94792259-0022cf80-03d9-11eb-8926-9734bfaa743b.png)

**Comment by codstar** [comment]
Fet a local.

**Comment by andriusmp** [comment]
OK
