### ISSUE TITLE
Alçada de les barres de la pàgina 'Projecte i escenaris'

### ISSUE THREAD

**Issue by andriusmp** [andriusmp/edit_org#3]
Les barres que contenen els diferents períodes / categories de centre haurien de tenir més alçada, per a que el text que contenen respiri millor.
Proposta gràfica:
![image](https://user-images.githubusercontent.com/42779858/90403001-99538c00-e0a0-11ea-8d8e-d5b78bbe2d70.png)

Com està ara:
![image](https://user-images.githubusercontent.com/42779858/90402975-8d67ca00-e0a0-11ea-8b03-4e6a9a43b536.png)

**Comment by codstar** [comment]
Fet a local.

**Comment by andriusmp** [comment]
OK
