### ISSUE TITLE
Favicon + logo

### ISSUE THREAD

**Issue by andriusmp** [andriusmp/edit_org#4]
T'enviem PNGs per canviar el 'èdit' que surt a dalt a l'esquerra (perquè ara mateix hi ha problemes amb la tipo i el símbol de la 'e') i el favicon (que no ens n'havíem adonat, ara segueix sent blau).
![image](https://user-images.githubusercontent.com/42779858/90403582-7bd2f200-e0a1-11ea-8348-f79f8dd3b881.png)

**Comment by codstar** [comment]
Fet a local.

**Comment by andriusmp** [comment]
OK

Faltaria canviar el text de la pantalla d'inici perquè no tingui problemes de tipo, com ens vas comentar (escriure èdit amb accent):
![image](https://user-images.githubusercontent.com/42779858/94573309-3f82dc00-0272-11eb-944c-ce47a5508da1.png)

**Comment by codstar** [comment]
Fet a local.

**Comment by andriusmp** [comment]
OK
