### ISSUE TITLE
Gris inèdit

### ISSUE THREAD

**Issue by andriusmp** [andriusmp/edit_org#5]
El text del nom del projecte està en negre, i hauria de ser gris inèdit
![image](https://user-images.githubusercontent.com/42779858/90404044-1c291680-e0a2-11ea-8ecb-c690a6b29add.png)

(en cap cas a la web s'hauria d'utilitzar el color negre, si no el gris inèdit #2E2B2B)

**Comment by codstar** [comment]
Fet a local.

**Comment by andriusmp** [comment]
OK
