### ISSUE TITLE
Textos a canviar (que no estan al traductor de text estàtic

### ISSUE THREAD

**Issue by andriusmp** [andriusmp/edit_org#6]
- Nom d'usuari de creació d'escenaris: inèdit hauria de portar accent i podem esborrar el punt final
![image](https://user-images.githubusercontent.com/42779858/90404292-82ae3480-e0a2-11ea-9bbc-70d0a7bc2be6.png)

- Creació d'escenaris > duplicate produced units --> No està al traductor de textos
- A l'Excel de resultats, la pestanya 'Consumption' no es tradueix
- Quan es mostren les taules de resultats d'impactes per a cada etapa i categoria d'impacte, la tercera opció/pestanya només mostra el 'Per' i no està al traductor de textos
![image](https://user-images.githubusercontent.com/42779858/91465641-535faa80-e88e-11ea-8789-16748c9285e5.png)

**Comment by codstar** [comment]
1) el autor que surt es el nom i cognom de l'usuari. A l'usuari inedit li he canviat el nom per a afegir l'accent. El cognom es un camp obligatori, ho he canvit per "_" de moment. No se si voleu que ho canvie per a permitir cognoms buits per a tots els usuaris
2) Fet a local
3) La paraula 'Consumption' no la teniu traduida al català encara. I ha més paraules que no teniu traduides. (Pero no modifiqueu més traduccions fins que no puje nova versió, ja us avisaré)
4) La paraula "Per" si està al traductor. Té format especial, surt aixi:  Per %(activity_variable)s

**Comment by andriusmp** [comment]
1/ OK, està bé així!
2/ OK
3/ OK
4/ OK, però llavors el problema és que no s'està completant la variable activity_variable, perquè a la interfície surt només el 'Per' (que no tradueixo perquè es quedaria igual en català)

*/ No sé què està passant ara, però l'eina de traducció es talla per l'esquerra:
![image](https://user-images.githubusercontent.com/42779858/94582059-1bc49380-027c-11eb-8827-a4696f815e59.png)

**Comment by codstar** [comment]
4) El nom de la variable d'activitat l'haveu de configurar per a cada projecte. Si no fiqueu res, no surtirà res. ;)
(Ho he mirat i al projecte "Petjada de carboni i petjada hídrica - Testing 2020" no està configurat aquest nom)

5) Eina de traducció es talla per l'esquerra: resolt a local

**Comment by andriusmp** [comment]
4. OK! No ho sabia! Moltes gràcies 👍 
5. OK
