### ISSUE TITLE
Espais entre períodes

### ISSUE THREAD

**Issue by andriusmp** [andriusmp/edit_org#7]
A la pàgina de projectes i escenaris, hi hauria d'haver més espai entre un període i un altre.
Proposta:
![image](https://user-images.githubusercontent.com/42779858/90404906-547d2480-e0a3-11ea-9157-68542043db1a.png)

Ara mateix està:
![image](https://user-images.githubusercontent.com/42779858/90404872-462f0880-e0a3-11ea-9484-b04209bf6e69.png)

També hi hauria d'haver més espai a la dreta i a sota:
![image](https://user-images.githubusercontent.com/42779858/90405041-8abaa400-e0a3-11ea-87d6-c0e94dc137e6.png)

**Comment by codstar** [comment]
Fet a local.

**Comment by andriusmp** [comment]
OK
