### ISSUE TITLE
Unificar capses gris clar amb barra mostassa

### ISSUE THREAD

**Issue by andriusmp** [andriusmp/edit_org#9]
Totes les capses gris clar que tenen barra mostassa (inventari, resultats, etc.) haurien de:
- Tenir la mateixa amplada dintre de la mateixa pàgina (ex: l'apartat 'Històrico de escenario' hauria de tenir el mateix ample que la resta d'inventari) (exemple 2: impactes totals amb resultats d'impacte per cada etapa)
![image](https://user-images.githubusercontent.com/42779858/90405568-39f77b00-e0a4-11ea-8f2a-b814ea33f971.png)
- La part mostassa no cal que sigui arrodonida, perquè si no ara queda un piuet blanc de la capsa de sota
![image](https://user-images.githubusercontent.com/42779858/90408771-9a88b700-e0a8-11ea-893b-83b7fcf80714.png)
- Els títols de la barra mostassa han de ser en Circular Std Bold

**Comment by codstar** [comment]
Fet a local.

**Comment by andriusmp** [comment]
- Amplades: OK
- Part mostassa quadrada: OK
- Tipo: hauria de ser Circular Std Bold, en comptes de Circular Std amb weight bold.

**Comment by codstar** [comment]
Jo si veig la font Circular Std Bold correcta, em pots dir un exemple on no estigui be?

**Comment by andriusmp** [comment]
OK
